version: '3'
services:
  redis:
    volumes:
      - redis-data:/data

  rabbitmq:
    volumes:
      - rabbit-data:/var/lib/rabbitmq

  postgres:
    volumes:
      - postgre-data:/var/lib/postgresql/data
      - ./config/extras/postgre_schemas.sh:/docker-entrypoint-initdb.d/postgre_schemas.sh

  mongo:
    volumes:
      - mongo-data:/data/db

  minio:
    volumes:
      - minio-data:/data

  influx:
    volumes:
      - influx-data:/var/lib/influxdb


  grafana:
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  postgre-data:
  rabbit-data:
  redis-data:
  minio-data:
  influx-data:
  grafana-data:
  mongo-data:
