# General server config
server:
  #  path: /
  #  proxy: true
  host: "0.0.0.0"
  port: 8080

# Local paths to modules and config
modules:
  plugins:
    provider:
      type: folder
      path: /data/pylon/plugins
  #
  requirements:
    mode: relaxed
    provider:
      type: folder
      path: /data/pylon/requirements
  #
  config:
    provider:
      type: folder
      path: /data/pylon/configs
  #
  preload:
    market:
      provider:
        type: git
        delete_git_dir: false
        depth: null
      source: https://github.com/carrier-io/market.git

configs:
  market:
    preordered_plugins:
      - auth
      - theme
      - shared
      - projects
      - security
      - secrets
      - tasks
      - artifacts
      - backend_performance
    plugin_repo:
      - type: config
        data:
          theme:
            source:
              type: git
              source: "https://github.com/carrier-io/theme.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/theme/next/metadata.json"
          shared:
            source:
              type: git
              source: "https://github.com/carrier-io/shared.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/shared/next/metadata.json"
          projects:
            source:
              type: git
              source: "https://github.com/carrier-io/projects.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/projects/next/metadata.json"
          security:
            source:
              type: git
              source: "https://github.com/carrier-io/security.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/security/next/metadata.json"
          secrets:
            source:
              type: git
              source: "https://github.com/carrier-io/secrets.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/secrets/next/metadata.json"
          tasks:
            source:
              type: git
              source: "https://github.com/carrier-io/tasks.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/tasks/next/metadata.json"
          artifacts:
            source:
              type: git
              source: "https://github.com/carrier-io/artifacts.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/artifacts/next/metadata.json"
          design-system:
            source:
              type: git
              source: "https://github.com/carrier-io/design-system.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/design-system/next/metadata.json"
          backend_performance:
            source:
              type: git
              source: "https://github.com/carrier-io/backend_performance.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/backend_performance/next/metadata.json"
      - type: resource
        name: data/plugins.json

# Session storage
sessions:
  redis:
    host: redis
    password: password
  prefix: pylon_session_

# Traefik config
traefik:
  redis:
    host: redis
    password: password
  rootkey: traefik
  entrypoint: http
  rule: PathPrefix(`/`)
  node_name: core
  node_hostname: pylon
  # node_url: http://pylon:8080

# Events queue
events:
  rabbitmq:
    host: rabbitmq
    port: 5672
    user: user
    password: password
    vhost: carrier
    queue: events
    hmac_key: key
    hmac_digest: sha512
    callback_workers: 16

# RPC
rpc:
  rabbitmq:
    host: rabbitmq
    port: 5672
    user: user
    password: password
    vhost: carrier
    queue: rpc
    hmac_key: key
    hmac_digest: sha512
    callback_workers: 16
  id_prefix: "core_"

# Module/config storage
storage:
  endpoint: minio:9000
  access_key: admin
  secret_key: password
  secure: false
  buckets:
    module: module
    config: config

# Loki logging settings
loki:
  buffering: true
  buffer_capacity: 70
  include_node_name: true
  include_level_name: true
  include_logger_name: true
  verify: true
  url: ${LOKI_HOST}


# Settings for Flask application
application:
  # EXPLAIN_TEMPLATE_LOADING: true
  # Sessions
  SECRET_KEY: SecretDevKeyForLocalUseOnlyChangedOnProd
  SESSION_COOKIE_NAME: session_id

# dulwich git manager
git_manager:
  default:
    username:
    password:
    key:
    key_data:
