
# General server config
server:
  name: worker
  path: /carrier-worker/
  proxy: true
  host: "0.0.0.0"
  port: 8080

# Local paths to modules and config
modules:
  plugins:
    provider:
      type: folder
      path: /data/pylon_worker/plugins
  #
  requirements:
    mode: relaxed
    provider:
      type: folder
      path: /data/pylon_worker/requirements
  #
  config:
    provider:
      type: folder
      path: /data/pylon_worker/configs
  #
  preload:
    market:
      provider:
        type: git
        delete_git_dir: false
        depth: null
      source: https://github.com/carrier-io/market.git

configs:
  market:
    preordered_plugins:
    - worker
    plugin_repo:
    - type: config
      data:
        worker:
          source:
            type: git
            source: "https://github.com/carrier-io/worker.git"
            branch: main
          objects:
            metadata: "https://raw.githubusercontent.com/carrier-io/worker/main/metadata.json"

# Events queue
# events:
#   rabbitmq:
#     host: rabbitmq
#     port: 5672
#     user: user
#     password: password
#     vhost: carrier
#     queue: worker-events
#     hmac_key: key
#     hmac_digest: sha512
#     callback_workers: 16

# RPC
# rpc:
#   rabbitmq:
#     host: rabbitmq
#     port: 5672
#     user: user
#     password: password
#     vhost: carrier
#     queue: worker-rpc
#     hmac_key: key
#     hmac_digest: sha512
#     callback_workers: 16
#   id_prefix: "worker_"

# Module/config storage
# storage:
#   endpoint: minio:9000
#   access_key: admin
#   secret_key: password
#   secure: false
#   buckets:
#     module: module
#     config: config

# Loki logging settings
loki:
  buffering: true
  buffer_capacity: 20
  include_node_name: true
  include_level_name: true
  include_logger_name: true
  verify: true
  url: ${LOKI_HOST}

# Settings for Flask application
application:
  # EXPLAIN_TEMPLATE_LOADING: true
  # Sessions
  SECRET_KEY: SecretDevKeyForLocalUseOnlyChangedOnProd
  # SESSION_COOKIE_NAME: worker_session_id

# dulwich git manager
git_manager:
  default:
    username:
    password:
    key:
    key_data:
